#http.listener.configuration
http.listener.host=localhost
http.listener.port=8081
http.listener.path=/durgapro


#http.request.configuration
http.request.host=training4-american-ws.cloudhub.io
http.request.port=80
http.request.path=/api/flights